import assert from 'node:assert/strict'
import { chmodSync, existsSync, mkdtempSync, mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { delimiter, join, resolve } from 'node:path'
import { spawn, spawnSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'
import { test } from 'node:test'

const testbedDir = fileURLToPath(new URL('../', import.meta.url))
const repoRoot = resolve(testbedDir, '..')
const probe = process.env.PROBE_UNDER_TEST || join(testbedDir, 'probes/boot-probe.sh')
const realHelper = join(testbedDir, 'probes/rpc-contract.mjs')
const syntheticToken = 'SYNTHETIC_STARTUP_TOKEN'
const syntheticLogToken = 'SYNTHETIC_LOG_TOKEN'
const responseMarker = 'SYNTHETIC_RESPONSE_BODY_MUST_NOT_LEAK'
const advertisedClient = '/plugins/??dsh-quota-panel/client.js&rev=quota-real-42'

function executable(path, content) {
  writeFileSync(path, content)
  chmodSync(path, 0o755)
}

function makeFixture(t, scenario = 'success') {
  const dir = mkdtempSync(join(tmpdir(), 'quota-boot-probe-'))
  t.after(() => rmSync(dir, { recursive: true, force: true }))
  const bin = join(dir, 'bin')
  const work = join(dir, 'work')
  const home = join(dir, 'dsh-home')
  mkdirSync(bin)
  mkdirSync(work)
  mkdirSync(home)

  const dshTrace = join(dir, 'dsh.args')
  const curlTrace = join(dir, 'curl.trace')
  const helperTrace = join(dir, 'helper.trace')
  const reaped = join(dir, 'dsh.reaped')
  const boot = join(dir, 'boot.html')
  const specs = join(dir, 'specs.json')
  writeFileSync(boot, '<!doctype html><script>window.__DSH_BOOT__ = {"meta":{"shape":"representative-real-boot"},"plugins":[{"url":"/plugins/??dsh-quota-panel/client.js&amp;rev=quota-real-42","platform":"web","enabled":true,"id":"dsh-quota-panel"}]};</script>\n')
  writeFileSync(specs, scenario === 'bad-specs'
    ? JSON.stringify({ type: 'server-response', rpcId: 'wrong-id', result: { ok: false, error: { message: responseMarker } } })
    : JSON.stringify({ type: 'server-response', rpcId: 'testbed-probe', result: { ok: true, value: { rows: [], refreshMs: 60000 } } }))

  executable(join(bin, 'dsh'), [
    '#!/usr/bin/env bash',
    'set -eu',
    'printf "%s\\n" "$*" > "$STUB_DSH_TRACE"',
    'printf "%s\\n" "$$" > "$STUB_DSH_PID_FILE"',
    'if [ "${STUB_DSH_TOKEN_MODE:-present}" != missing ]; then',
    '  printf "open http://127.0.0.1:3080/?token=%s\\n" "$STUB_SECRET_TOKEN"',
    'fi',
    'printf "diagnostic token = %s\\n" "$STUB_LOG_TOKEN"',
    "trap 'sleep 0.15; printf \"terminated\\n\" > \"$STUB_DSH_REAPED\"; exit 0' TERM INT HUP",
    'while :; do sleep 0.05; done',
    '',
  ].join('\n'))

  executable(join(bin, 'curl'), [
    '#!/usr/bin/env bash',
    'set -u',
    'out=""; cookie_out=""; method=GET; url=""; write_out=""; data_body=""; have_connect=0; have_max=0; follow=0',
    'while [ "$#" -gt 0 ]; do',
    '  case "$1" in',
    '    --connect-timeout) have_connect=1; connect_value="$2"; shift 2 ;;',
    '    --max-time) have_max=1; max_value="$2"; shift 2 ;;',
    '    --location|-L) follow=1; shift ;;',
    '    -o|--output) out="$2"; shift 2 ;;',
    '    -c|--cookie-jar) cookie_out="$2"; shift 2 ;;',
    '    -w|--write-out) write_out="$2"; shift 2 ;;',
    '    -d|--data|--data-raw) data_body="$2"; shift 2 ;;',
    '    -b|--cookie|-H|--header) shift 2 ;;',
    '    -X|--request) method="$2"; shift 2 ;;',
    '    -*) shift ;;',
    '    *) url="$1"; shift ;;',
    '  esac',
    'done',
    'printf "%s\\t%s\\t%s\\t%s\\t%s\\t%s\\n" "$method" "$url" "${connect_value:-missing}" "${max_value:-missing}" "$follow" "$data_body" >> "$STUB_CURL_TRACE"',
    'if [ "$have_connect" -ne 1 ] || [ "$have_max" -ne 1 ]; then printf 000; exit 90; fi',
    'write_body() { [ -z "$out" ] || printf "%s" "$1" > "$out"; }',
    'if [ "${STUB_CURL_SCENARIO:-success}" = connect-fail ]; then printf 000; exit 7; fi',
    'case "$url" in',
    '  *"?token="*)',
    '    if [ "$follow" -ne 1 ]; then write_body "redirect"; printf 303; exit 0; fi',
    '    if [ -n "$cookie_out" ]; then',
    '      printf "# Netscape HTTP Cookie File\\n# generated by stub\\n" > "$cookie_out"',
    '      if [ "${STUB_CURL_SCENARIO:-success}" != no-cookie ]; then printf "#HttpOnly_127.0.0.1\\tFALSE\\t/\\tFALSE\\t0\\tdsh_session\\tstub-value\\n" >> "$cookie_out"; fi',
    '    fi',
    '    write_body "authenticated"',
    '    effective="http://127.0.0.1:${PORT_UNDER_TEST}/"',
    '    if [ "${STUB_CURL_SCENARIO:-success}" = cross-origin-auth ]; then effective="http://elsewhere.invalid/"; fi',
    '    case "$write_out" in *url_effective*) printf "200\\t%s" "$effective" ;; *) printf 200 ;; esac; exit 0 ;;',
    '  "http://127.0.0.1:${PORT_UNDER_TEST}/")',
    '    if [ "${STUB_CURL_SCENARIO:-success}" = total-timeout ]; then printf 000; exit 28; fi',
    '    if [ "${STUB_CURL_SCENARIO:-success}" = auth-forbidden ]; then write_body forbidden; printf 403; exit 0; fi',
    '    [ -z "$out" ] || cp "$STUB_BOOT_FILE" "$out"; printf 200; exit 0 ;;',
    '  "http://127.0.0.1:${PORT_UNDER_TEST}/plugins/??dsh-quota-panel/client.js&rev=quota-real-42")',
    '    write_body "export default true"',
    '    if [ "${STUB_CURL_SCENARIO:-success}" = die-after-client ]; then kill -KILL "$(cat "$STUB_DSH_PID_FILE")" 2>/dev/null || true; fi',
    '    printf 200; exit 0 ;;',
    '  "http://127.0.0.1:${PORT_UNDER_TEST}/api/dsh-quota-panel/specs")',
    '    if [ "${STUB_CURL_SCENARIO:-success}" = die-on-missing-route ]; then kill -KILL "$(cat "$STUB_DSH_PID_FILE")" 2>/dev/null || true; write_body "$STUB_RESPONSE_MARKER"; printf 405; exit 0; fi',
    '    if [ "${STUB_CURL_SCENARIO:-success}" = route-missing ]; then write_body "$STUB_RESPONSE_MARKER"; printf 405; exit 0; fi',
    '    if [ "${STUB_CURL_SCENARIO:-success}" = specs-forbidden ]; then write_body forbidden; printf 403; exit 0; fi',
    '    [ -z "$out" ] || cp "$STUB_SPECS_FILE" "$out"; printf 200; exit 0 ;;',
    '  *) write_body not-found; printf 404; exit 0 ;;',
    'esac',
    '',
  ].join('\n'))

  const helperWrapper = join(dir, 'contract-helper-stub.mjs')
  writeFileSync(helperWrapper, [
    "import { appendFileSync } from 'node:fs'",
    "import { spawnSync } from 'node:child_process'",
    "appendFileSync(process.env.STUB_HELPER_TRACE, JSON.stringify(process.argv.slice(2)) + '\\n')",
    "if (process.env.STUB_HELPER_FETCH_ALL === '1' && process.argv[2] === 'contract') { process.stdout.write(JSON.stringify({ route: '/api/dsh-quota-panel/fetch-all', method: 'dsh-quota-panel/fetch-all' }) + '\\n'); process.exit(0) }",
    "if (process.env.STUB_HELPER_HANG === process.argv[2]) await new Promise(resolve => setTimeout(resolve, 5_000))",
    'const result = spawnSync(process.execPath, [process.env.REAL_CONTRACT_HELPER, ...process.argv.slice(2)], { stdio: \'inherit\' })',
    'process.exit(result.status ?? 1)',
    '',
  ].join('\n'))

  const env = {
    ...process.env,
    PATH: `${bin}${delimiter}${process.env.PATH ?? ''}`,
    DSH_VERSION: 'test-version',
    GRID_LABEL: 'stub-flow',
    DSH_HOME: home,
    PLUGIN_DIR: repoRoot,
    CONTRACT_HELPER: helperWrapper,
    REAL_CONTRACT_HELPER: realHelper,
    STUB_HELPER_TRACE: helperTrace,
    STUB_HELPER_HANG: scenario === 'contract-hang' ? 'contract' : scenario === 'client-helper-hang' ? 'client-url' : '',
    STUB_HELPER_FETCH_ALL: scenario === 'fetch-all-contract' ? '1' : '0',
    STUB_DSH_TRACE: dshTrace,
    STUB_DSH_REAPED: reaped,
    STUB_DSH_PID_FILE: join(dir, 'dsh.pid'),
    STUB_DSH_TOKEN_MODE: scenario === 'missing-token' ? 'missing' : 'present',
    STUB_SECRET_TOKEN: syntheticToken,
    STUB_LOG_TOKEN: syntheticLogToken,
    STUB_CURL_TRACE: curlTrace,
    STUB_CURL_SCENARIO: scenario,
    STUB_BOOT_FILE: boot,
    STUB_SPECS_FILE: specs,
    STUB_RESPONSE_MARKER: responseMarker,
    PORT_UNDER_TEST: '31999',
    PORT: '31999',
    WORK_DIR: work,
    LOG: join(work, 'dsh-web.log'),
    COOKIE: join(work, 'cookies.txt'),
    L2_DEADLINE_SECONDS: scenario === 'contract-hang' ? '1' : scenario === 'client-helper-hang' ? '3' : '5',
    L2_POLL_SECONDS: scenario === 'missing-token' ? '5' : '0.02',
    CURL_CONNECT_TIMEOUT: '1',
    CURL_MAX_TIME: '1',
    FAIL_LOG_LINES: '20',
  }
  return { dir, work, env, dshTrace, curlTrace, helperTrace, reaped }
}

function runProbe(t, scenario = 'success') {
  const fixture = makeFixture(t, scenario)
  const started = Date.now()
  const result = spawnSync('bash', [probe], {
    cwd: repoRoot,
    env: fixture.env,
    encoding: 'utf8',
    timeout: 7000,
  })
  return { ...fixture, ...result, elapsedMs: Date.now() - started, output: `${result.stdout}${result.stderr}` }
}

async function signalProbe(t, signal) {
  const fixture = makeFixture(t)
  const child = spawn('bash', [probe], {
    cwd: repoRoot,
    env: fixture.env,
    stdio: ['ignore', 'pipe', 'pipe'],
  })
  let output = ''
  child.stdout.setEncoding('utf8').on('data', chunk => { output += chunk })
  child.stderr.setEncoding('utf8').on('data', chunk => { output += chunk })
  const deadline = Date.now() + 5000
  while (!existsSync(fixture.env.STUB_DSH_PID_FILE)) {
    if (child.exitCode !== null) break
    if (Date.now() >= deadline) {
      child.kill('SIGKILL')
      assert.fail(`probe did not reach a signalable stage: ${output}`)
    }
    await new Promise(resolve => setTimeout(resolve, 20))
  }
  assert.equal(child.kill(signal), true, `failed to deliver ${signal}`)
  const settled = await Promise.race([
    new Promise(resolve => child.once('exit', (code, exitSignal) => resolve({ code, signal: exitSignal }))),
    new Promise(resolve => setTimeout(() => resolve({ timeout: true }), 5000)),
  ])
  if (settled.timeout) child.kill('SIGKILL')
  return { ...fixture, ...settled, output }
}

function readIfPresent(path) {
  return existsSync(path) ? readFileSync(path, 'utf8') : ''
}

function assertSensitiveFilesRemoved(result) {
  for (const name of ['cookies.txt', 'auth-body.txt', 'boot.html', 'quota-client.js', 'specs-body.json', 'rpc-contract.json']) {
    assert.equal(existsSync(join(result.work, name)), false, `${name} must be removed by cleanup`)
  }
}

function assertStoppedAndReaped(result) {
  assert.equal(result.signal, null, `probe timed out or was signalled: ${result.output}`)
  assert.equal(readIfPresent(result.reaped), 'terminated\n', 'EXIT trap must kill and wait for dsh web cleanup')
  assertSensitiveFilesRemoved(result)
}

function assertMissingTokenFailure(output) {
  const diagnostic = output.split(/\r?\n/).filter(line => /\[fail\]/.test(line)).find(line => (
    (/token/i.test(line) && /未取得/.test(line)) ||
    (/(?:截止时间|deadline)/i.test(line) && /(?:等待|耗尽)/.test(line) && /启动\s*token/i.test(line))
  ))
  assert.ok(diagnostic, `missing-token failure must report unavailable startup token on one fail line: ${output}`)
}

function helperModes(result) {
  return readIfPresent(result.helperTrace).trim().split('\n').filter(Boolean).map(line => JSON.parse(line)[0])
}

test('rpc-contract CLI exposes only safe contract, client URL, validation summary, and redacted logs', t => {
  const dir = mkdtempSync(join(tmpdir(), 'quota-contract-cli-'))
  t.after(() => rmSync(dir, { recursive: true, force: true }))
  const boot = join(dir, 'boot.html')
  const body = join(dir, 'body.json')
  writeFileSync(boot, '<script>window.__DSH_BOOT__={"plugins":[{"id":"dsh-quota-panel","url":"/plugins/??dsh-quota-panel/client.js&amp;rev=cli-1"}]}</script>')
  writeFileSync(body, JSON.stringify({ type: 'server-response', rpcId: 'cli-probe', result: { ok: true, value: { rows: [], refreshMs: 60000 } } }))

  const contract = spawnSync(process.execPath, [realHelper, 'contract', repoRoot], { encoding: 'utf8' })
  assert.equal(contract.status, 0, contract.stderr)
  assert.deepEqual(JSON.parse(contract.stdout), {
    route: '/api/dsh-quota-panel/specs',
    method: 'dsh-quota-panel/specs',
  })
  assert.doesNotMatch(contract.stdout, /fetch-all/)

  const client = spawnSync(process.execPath, [realHelper, 'client-url', boot], { encoding: 'utf8' })
  assert.equal(client.status, 0, client.stderr)
  assert.equal(client.stdout, '/plugins/??dsh-quota-panel/client.js&rev=cli-1\n')

  const validated = spawnSync(process.execPath, [realHelper, 'validate-specs', body, 'cli-probe', '60000'], { encoding: 'utf8' })
  assert.equal(validated.status, 0, validated.stderr)
  assert.equal(validated.stdout, 'specs rows=0 refreshMs=60000\n')

  const redacted = spawnSync(process.execPath, [realHelper, 'redact-log', '-'], {
    input: `open ?token=${syntheticToken}&next=1 token = ${syntheticLogToken}\n`,
    encoding: 'utf8',
  })
  assert.equal(redacted.status, 0, redacted.stderr)
  assert.equal(redacted.stdout, 'open ?token=[REDACTED]&next=1 token = [REDACTED]\n')
})

test('real shell flow requires --no-open, authenticates, GETs advertised revision, and validates dynamic specs', t => {
  const result = runProbe(t)
  assert.equal(result.status, 0, result.output)
  assert.equal(readFileSync(result.dshTrace, 'utf8'), 'web --no-open\n')
  const calls = readFileSync(result.curlTrace, 'utf8').trim().split('\n').map(line => line.split('\t'))
  assert.ok(calls.length >= 4, result.output)
  assert.ok(calls.every(([, , connect, max]) => connect === '1' && max === '1'), 'every curl call must set connect and total timeouts')
  assert.ok(calls.some(([method, url, , , follow]) => method === 'GET' && url.includes('/?token=') && follow === '1'), 'token exchange must follow the 303 redirect to a final 200 and cookie')
  assert.ok(calls.some(([method, url]) => method === 'GET' && url === `http://127.0.0.1:31999${advertisedClient}`), 'advertised revisioned client URL must be actually fetched')
  const specsCall = calls.find(([method, url]) => method === 'POST' && url === 'http://127.0.0.1:31999/api/dsh-quota-panel/specs')
  assert.ok(specsCall, 'dynamic specs route must be POSTed')
  assert.deepEqual(JSON.parse(specsCall[5]), {
    type: 'client-request',
    rpcId: 'testbed-probe',
    method: 'dsh-quota-panel/specs',
    payload: null,
  })
  assert.notEqual(JSON.parse(specsCall[5]).method, 'dsh-quota-panel/fetch-all')
  assert.deepEqual(helperModes(result), ['contract', 'client-url', 'validate-specs'])
  assert.match(result.output, /L2 全部通过/)
  assert.doesNotMatch(result.output, new RegExp(`${syntheticToken}|${syntheticLogToken}`))
  assertStoppedAndReaped(result)
  assert.equal(statSync(join(result.work, 'dsh-web.log')).mode & 0o077, 0, 'probe-created log must deny group/other access under umask 077')
})

for (const [signal, expected] of [['SIGHUP', 129], ['SIGINT', 130], ['SIGTERM', 143]]) {
  test(`real probe exits nonzero and reaps dsh on ${signal}`, async t => {
    const result = await signalProbe(t, signal)
    assert.equal(result.timeout, undefined, `${signal} did not terminate the probe: ${result.output}`)
    const status = result.code ?? (result.signal ? 128 + ({ SIGHUP: 1, SIGINT: 2, SIGTERM: 15 }[result.signal] ?? 0) : 0)
    assert.equal(status, expected, `${signal} must preserve shell signal status: ${result.output}`)
    assert.equal(readIfPresent(result.reaped), 'terminated\n', `${signal} must reap dsh before exit`)
    assertSensitiveFilesRemoved(result)
  })
}

test('dynamic contract cannot redirect the probe to fetch-all', t => {
  const result = runProbe(t, 'fetch-all-contract')
  assert.notEqual(result.status, 0, result.output)
  assert.match(result.output, /动态 specs contract 不符/)
  assert.equal(existsSync(result.curlTrace), false, 'fetch-all contract must fail before any curl request')
})

test('auth redirect must stay on the expected loopback home origin', t => {
  const result = runProbe(t, 'cross-origin-auth')
  assert.notEqual(result.status, 0, result.output)
  assert.match(result.output, /认证重定向目标不符/)
  assert.doesNotMatch(result.output, /elsewhere\.invalid/)
  assertStoppedAndReaped(result)
})

test('missing-token diagnostic helper binds semantics to a fail line', async t => {
  for (const output of [
    '[testbed][test-version][stub-flow][l2] [fail] 截止时间内未取得启动 token\ndiagnostic token = [REDACTED]\n',
    '[testbed][test-version][stub-flow][l2] [fail] 全流程截止时间耗尽（等待启动 token）\ndiagnostic token = [REDACTED]\n',
  ]) {
    await t.test(`accepts ${JSON.stringify(output.split('\n')[0])}`, () => {
      assert.doesNotThrow(() => assertMissingTokenFailure(output))
    })
  }

  for (const output of [
    '[testbed][test-version][stub-flow][l2] [fail] 全流程截止时间耗尽（等待首页）\ndiagnostic token = [REDACTED]\n',
    '[testbed][test-version][stub-flow][l2] [fail] 全流程截止时间耗尽（读取 specs route）\ndiagnostic token = [REDACTED]\n',
    'diagnostic token = [REDACTED]\n',
  ]) {
    await t.test(`rejects ${JSON.stringify(output.split('\n')[0])}`, () => {
      assert.throws(() => assertMissingTokenFailure(output))
    })
  }
})

test('missing startup token and missing session cookie both fail closed', async t => {
  await t.test('token is mandatory', t => {
    const result = runProbe(t, 'missing-token')
    assert.notEqual(result.status, 0, result.output)
    assertMissingTokenFailure(result.output)
    assert.match(result.output, /token\s*=\s*\[REDACTED\]/i)
    assert.doesNotMatch(result.output, new RegExp(`${syntheticToken}|${syntheticLogToken}`))
    assertStoppedAndReaped(result)
  })
  await t.test('cookie jar must contain a real record, not only Netscape headers', t => {
    const result = runProbe(t, 'no-cookie')
    assert.notEqual(result.status, 0, result.output)
    assert.match(result.output, /cookie.*未建立|未建立.*cookie/i)
    assert.doesNotMatch(result.output, new RegExp(`${syntheticToken}|${syntheticLogToken}`))
    assertStoppedAndReaped(result)
  })
})

for (const scenario of ['contract-hang', 'client-helper-hang']) {
  test(`${scenario} is bounded by the whole-flow deadline and reaps dsh`, t => {
    const result = runProbe(t, scenario)
    assert.notEqual(result.status, 0, result.output)
    assert.equal(result.signal, null, `outer test timeout fired instead of the probe deadline: ${result.output}`)
    const allowanceMs = scenario === 'contract-hang' ? 3000 : 6000
    assert.ok(result.elapsedMs < allowanceMs, `probe exceeded its bounded test allowance: ${result.elapsedMs}ms`)
    assert.match(result.output, /截止时间|deadline|timeout/i)
    if (scenario === 'client-helper-hang') {
      assert.match(result.output, /启动 token 与 session cookie 均已取得/)
      assert.match(result.output, /认证首页 HTTP 200/)
      assert.deepEqual(helperModes(result), ['contract', 'client-url', 'redact-log'])
      assertStoppedAndReaped(result)
    }
  })
}

for (const [scenario, diagnostic] of [
  ['connect-fail', /curl.*7|连接/i],
  ['total-timeout', /curl.*28|超时/i],
]) {
  test(`${scenario} curl failure cannot produce a passing probe`, t => {
    const result = runProbe(t, scenario)
    assert.notEqual(result.status, 0, result.output)
    assert.match(result.output, diagnostic)
    assert.doesNotMatch(result.output, /L2 全部通过/)
    assertStoppedAndReaped(result)
  })
}

test('HTTP 200 with a bad specs envelope fails through the existing contract helper without body echo', t => {
  const result = runProbe(t, 'bad-specs')
  assert.notEqual(result.status, 0, result.output)
  assert.match(result.output, /specs.*契约|契约.*specs/i)
  assert.ok(helperModes(result).includes('validate-specs'), 'the shell must delegate JSON semantics to rpc-contract.mjs')
  assert.doesNotMatch(result.output, new RegExp(responseMarker))
  assertStoppedAndReaped(result)
})

for (const [scenario, expected] of [
  ['die-after-client', /dsh web.*客户端.*退出|客户端.*dsh web.*退出/i],
  ['die-on-missing-route', /dsh web.*specs.*退出|specs.*dsh web.*退出/i],
]) {
  test(`${scenario} cannot be classified as a successful route-missing negative`, t => {
    const result = runProbe(t, scenario)
    assert.notEqual(result.status, 0, result.output)
    assert.match(result.output, expected)
    assert.doesNotMatch(result.output, /specs 路由缺失/)
    assert.equal(result.signal, null, result.output)
  })
}

test('specs 401/403 is classified as authentication failure, never route missing', t => {
  const result = runProbe(t, 'specs-forbidden')
  assert.notEqual(result.status, 0, result.output)
  assert.match(result.output, /specs \/api 会话认证被拒绝（HTTP 403）/)
  assert.doesNotMatch(result.output, /路由缺失/)
  assertStoppedAndReaped(result)
})

test('missing specs route fails only after auth, home, and revisioned client pass; failure logs redact tokens', t => {
  const result = runProbe(t, 'route-missing')
  assert.notEqual(result.status, 0, result.output)
  const calls = readFileSync(result.curlTrace, 'utf8').trim().split('\n').map(line => line.split('\t'))
  const authIndex = calls.findIndex(([method, url, , , follow]) => method === 'GET' && url.includes('/?token=') && follow === '1')
  const homeIndex = calls.findIndex(([method, url]) => method === 'GET' && url === 'http://127.0.0.1:31999/')
  const clientIndex = calls.findIndex(([method, url]) => method === 'GET' && url === `http://127.0.0.1:31999${advertisedClient}`)
  const specsIndex = calls.findIndex(([method, url]) => method === 'POST' && url === 'http://127.0.0.1:31999/api/dsh-quota-panel/specs')
  assert.ok(authIndex >= 0 && authIndex < homeIndex, 'auth redirect and cookie must complete before the home probe')
  assert.ok(homeIndex < clientIndex && clientIndex < specsIndex, 'home and advertised client must pass before the missing route is exercised')
  assert.match(result.output, /路由缺失.*405|405.*路由缺失/)
  assert.match(result.output, /token=\[REDACTED\]/i)
  assert.doesNotMatch(result.output, new RegExp(`${syntheticToken}|${syntheticLogToken}|${responseMarker}`))
  assert.ok(helperModes(result).includes('redact-log'), 'failure log output must pass through redactLog')
  assertStoppedAndReaped(result)
})
